"""Parser tests: verify page numbers and section breadcrumbs are extracted.

Binary fixtures (sample.pdf, sample.docx) are generated by
``tests/fixtures/generate_fixtures.py`` and committed to the repo.
"""

from pathlib import Path

from app.services.parsing import parse_document

FIXTURES = Path(__file__).parent / "fixtures"


def _block_with(blocks, marker):
    return next(block for block in blocks if marker in block.text)


def test_markdown_extracts_section_path() -> None:
    blocks = parse_document(FIXTURES / "sample.md")

    section_21 = _block_with(blocks, "MarkdownSection21")
    assert section_21.section_path == "Chapter 2 > Section 2.1"
    assert section_21.page_number is None

    section_11 = _block_with(blocks, "MarkdownSection11")
    assert section_11.section_path == "Chapter 1 > Section 1.1"


def test_html_extracts_section_path() -> None:
    blocks = parse_document(FIXTURES / "sample.html")

    section_21 = _block_with(blocks, "HtmlSection21")
    assert section_21.section_path == "Chapter 2 > Section 2.1"
    assert section_21.page_number is None


def test_docx_extracts_section_path() -> None:
    blocks = parse_document(FIXTURES / "sample.docx")

    section_21 = _block_with(blocks, "DocxSection21")
    assert section_21.section_path == "Chapter 2 > Section 2.1"
    assert section_21.page_number is None


def test_pdf_extracts_page_numbers() -> None:
    blocks = parse_document(FIXTURES / "sample.pdf")

    assert len(blocks) == 2
    assert _block_with(blocks, "PdfPageOne").page_number == 1
    assert _block_with(blocks, "PdfPageTwo").page_number == 2
    # PDFs have no heading hierarchy in this pipeline.
    assert all(block.section_path is None for block in blocks)
